name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./Android/FreshFitness/gradlew
    
    - name: Touch local.properties
      run: touch ./Android/FreshFitness/local.properties
    
    - name: Add Api Key
      run: echo "MAPS_API_KEY=\"\"" >> ./Android/FreshFitness/local.properties

    - name: Touch key.properties
      run: touch ./Android/FreshFitness/key.properties
    
    - name: Add base URL for S3
      run: echo "S3_IMAGES_BASE_URL=\"\"" >> ./Android/FreshFitness/key.properties
    
    - name: Build with Gradle
      run: ./Android/FreshFitness/gradlew build
